### ISSUE TITLE
Error with the (<) operator and Nat.maxNat ?

### ISSUE THREAD

**Issue by FlorianBELLAZOUZ** [unisonweb/unison#2591]
Maybe I misunderstand something.
Just in case  :
```unison
> 0 < Nat.maxNat -- return false, but i expect true
> 123949 < Nat.maxNat -- return false, but i expect true
> Nat.maxNat -- return 18446744073709551615 
> 0 < 18446744073709551615 -- return false, but I expect true
> 0 < 18446744073709551610 -- return false, but I expect true
> 0 < 1844674407370955161 -- return true, and I expect true 
```
I run that on release/M2j

**Comment by atacratic** [comment]
Should be fixed in master and the next release 🙂 see #2083

**Comment by FlorianBELLAZOUZ** [comment]
It's better but there are still a problem in version 94cbf78

```
> 0 < Nat.maxNat
           ⧩
           false

> 0 < 18446744073709551615
           ⧩
           false
  
> 0 < 18446744073709551614
           ⧩
           true 
```

**Comment by atacratic** [comment]
@dolio ?

**Comment by pchiusano** [comment]
Thanks for (re)reporting.

@dolio it looks like we missed adding tests for this in that PR and I didn't spot in my review. 

I'm guessing the culprit is a `fromIntegral` call on the underlying `Int` when you want instead a bitwise cast. It seems like a coerce would do it. Also be sure to add tests. :)

**Comment by dolio** [comment]
That isn't what happens using the latest trunk on my machine. Is that a cached answer?

**Comment by pchiusano** [comment]
Oh... yeah that is probably it. @FlorianBELLAZOUZ try `debug.clear-cache` in `ucm` and then try again. I get:

<img width="845" alt="Screen Shot 2021-11-05 at 3 42 15 PM" src="https://user-images.githubusercontent.com/11074/140576008-2d239dac-f6cd-4f4a-80d5-8a7222e06189.png">

**Comment by pchiusano** [comment]
incidentally, the red arrow indicates the value is not found in the cache, and the black arrow means it was found in the cache.

**Comment by pchiusano** [comment]
I'm still confused about the use of `fromIntegral` since I thought that would do the wrong thing.

**Comment by FlorianBELLAZOUZ** [comment]
After the debug.clear-cache it work as expected 

```
> 0 < Nat.maxNat
          ⧩
          true
  
> 0 < 18446744073709551615
          ⧩
          true
  
> 0 < 18446744073709551614
          ⧩
          true
```

So sorry for the false alert.

**Comment by dolio** [comment]
No worries. The cache tricks me all the time.
