### ISSUE TITLE
Don't show __projects in output

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#4702]
Whenever the names output includes `__projects.<uuid>.branches.<uuid>`, we want to:

A) Show the project name and branch (`@unison/base/main`)
B) Or, if easier, remove that prefix from the output since it's always (?) the currently active project anyway.

---

@aryairani asked us to collect occurrences, below is a list:

### Delete
Trying to delete a type that was in use somewhere (release 0.5.16):

![CleanShot 2024-02-15 at 11 11 41@2x](https://github.com/unisonweb/unison/assets/2371/88faa83e-b2cd-47e9-a763-81ae9da4751a)

### Upgrade
Trying to upgrade where the namespaces are missing (release 0.5.17):

![CleanShot 2024-02-17 at 11 50 16@2x](https://github.com/unisonweb/unison/assets/2371/d9123b49-3c25-400c-ad8a-076aa1445ce5)

### Namespace.Dependencies (release 0.5.17)
![CleanShot 2024-02-22 at 12 30 20@2x](https://github.com/unisonweb/unison/assets/2371/049525a3-2fbf-4e4a-9d8c-d1e6f6410798)

**Comment by hojberg** [comment]
I don't know if this is still happening, but its a recent and related ticket: https://github.com/unisonweb/unison/issues/4475 cc @stew

**Comment by hojberg** [comment]
Also seems related https://github.com/unisonweb/unison/issues/4131

**Comment by aryairani** [comment]
Any occurrences older than Jan 14, 2024 (for `trunk`) or Jan 22, 2024 (`release/0.5.14`) would need to be verified again, because most would have been fixed since then.

`delete` is a weird case, so I'm not surprised now that you mention it @hojberg

**Comment by hojberg** [comment]
I can confirm that the `upgrade` one still happens. Adding it to the description of this Issue.

**Comment by hojberg** [comment]
@aryairani I added another case in `namespace.dependencies`

**Comment by hojberg** [comment]
@aryairani found another in `reflog`:

![CleanShot 2024-03-19 at 14 39 37@2x](https://github.com/unisonweb/unison/assets/2371/d92bafb3-3295-43bf-8c50-5eee1aeb602b)
