### ISSUE TITLE
Command prompt very slow

### ISSUE THREAD

**Issue by zenhack** [unisonweb/unison#700]
I'm working with the codebase at https://github.com/zenhack/unison-parsers, and when saving a scratch file the console takes several seconds to respond. @aryairani is of the opinion this is probably a bug.

**Comment by zenhack** [comment]
Several other operations are having similar perf issues, including the edit command.

**Comment by atacratic** [comment]
dup of #631?

**Comment by zenhack** [comment]
Probably; I'll close this and post the link to my codebase there.

**Comment by aryairani** [comment]
@zenhack I renamed the ticket; it's not a dupe of #631.  It should be fixed in master though; please reopen if not.

**Comment by zenhack** [comment]
Yep, this one seems to be fixed.

(there are other perf issues still though...)

Quoting Arya Irani (2019-09-05 17:31:52)

**Comment by aryairani** [comment]
Yup let’s open separate tickets for each.
